### ISSUE TITLE
Consider licensing under the Apache-2.0 and/or MIT licenses?

### ISSUE THREAD

**Issue by iBelieve** [jmagnuson/ahrs-rs#21]
Thanks for your work porting the Mahony and Madgwick AHRS algorithms to Rust! I'd like to use this crate for a (likely open-source) project I'm working on, but would like to avoid the GPL license. Would you consider licensing this under the Apache-2.0 and/or MIT licenses, since those seem to be the most common for Rust crates?

**Comment by jmagnuson** [comment]
Thanks for the interest, licensing was definitely something I grappled with when first writing. Ultimately, it comes down to the original source implementation (GPL) which may or may not have been referenced while porting. IANAL so I simply chose to stay on the safe side, though I have thought about reaching out to Dr. Madgwick for any sort of blessing that may be offered. FWIW this is the only crate I maintain which isn't MIT/Apache-2.0, so I totally agree with your point of view.

**Comment by TheButlah** [comment]
Could you reach out to Dr. Madgwick? I think it would be really great if it were licensed like the rest of the Rust ecosystem

**Comment by TheButlah** [comment]
Not sure what that process looks like for it to be perpetually legal and free of license woes

**Comment by latenitefilms** [comment]
Dumb question... but the [link you have in README](https://x-io.co.uk/open-source-imu-and-ahrs-algorithms/), points to this GitHub repo which is [MIT licensed](https://github.com/xioTechnologies/Fusion/blob/main/LICENSE.md):

https://github.com/xioTechnologies/Fusion

Is it possible that the code you were originally referencing is now MIT licensed?

**Comment by latenitefilms** [comment]
I wonder if @xioTechnologies could jump in, and offer any insight?

**Comment by xioTechnologies** [comment]
[Fusion](https://github.com/xioTechnologies/Fusion) is _the_ algorithm repository.  All other repositories and code distributions are snapshots of the algorithm at different points in time.  For example, the [original source code](https://code.google.com/archive/p/imumargalgorithm30042010sohm/) accompanying the 2011 paper, the [C# and MATLAB](https://x-io.co.uk/open-source-imu-and-ahrs-algorithms/) ports, and the copies bundled with specific applications such as the [oscillatory motion](https://github.com/xioTechnologies/Oscillatory-Motion-Tracking-With-x-IMU) and [gait tracking](https://github.com/xioTechnologies/Gait-Tracking-With-x-IMU) examples.

Having so many versions of the code existing simultaneously is not ideal, but it is something I am slowly trying to rectify with all new occurrences being tracible back to the version controlled Fusion repository.

My preference is for code ports to be avoided in favour of wrapping of the C code.  This is already demonstrated with the Python package, [imufusion](https://pypi.org/project/imufusion/).  Wrapping reduces the risk of errors, allows the behaviour of the algorithm to be replicated identically on each platform, and significantly simplifies maintenance of implementations in other languages.

I will discuss the addition of a Rust crate to Fusion with my team.  We already use Rust FFI in another project so it should hopefully be straightforward.  In the meantime, I can confirm that I have no problem with you porting and distributing the old "Mahony and Madgwick" code.

Seb Madgwick

**Comment by TheButlah** [comment]
That's awesome to hear, sounds like we can indeed switch our license.

Was the `fusion` library always MIT? I only see MIT in the code history.

**Comment by xioTechnologies** [comment]
I cannot easily answer those questions.  I can tell you that I consider the [Fusion repository](https://github.com/xioTechnologies/Fusion) to supersede all past distributions, and represent how I wish the algorithm and library to exist in the public domain.

**Comment by jmagnuson** [comment]
That's great news! I'll go ahead and cut a new release under MIT to match `fusion`, thanks everyone.

**Comment by jmagnuson** [comment]
@latenitefilms sorry, I should have some time later today (US time) to do it + cut a release. But if you beat me to it that would be great too.

**Comment by jmagnuson** [comment]
[0.6.0](https://crates.io/crates/ahrs/0.6.0) has been published to crates.io under MIT!
