### ISSUE TITLE
Push new crates.io release

### ISSUE THREAD

**Issue by lennartkloock** [jmagnuson/ahrs-rs#25]
It would be nice if a new crates.io release would be pushed, since the version on crates.io (`0.3.0`) still works with nalgebra's `Quaternion` instead of `UnitQuaternion`.

**Comment by jmagnuson** [comment]
You probably saw this, but the `UnitQuaternion` change was made in #22 -- I just forgot to cut a release. Thanks for the reminder!

**Comment by jmagnuson** [comment]
Published [0.4.0](https://crates.io/crates/ahrs/0.4.0) to crates.io, as part of #26.
