### ISSUE TITLE
no_std support?

### ISSUE THREAD

**Issue by overheat** [jmagnuson/ahrs-rs#37]
Is it possiable to support `no_std` enviroment?

Looks `nalgebra` crate already support `no_std`
https://www.nalgebra.org/docs/user_guide/wasm_and_embedded_targets

**Comment by jmagnuson** [comment]
`no_std` support was added in #12. But `std` is a feature flag that is enabled by default, so `default-features = false` will need to be set in the `Cargo.toml`.

https://doc.rust-lang.org/cargo/reference/features.html#dependency-features

**Comment by overheat** [comment]
A wired issue:
```
    = note: perhaps two different versions of crate `nalgebra` are being used?
note: expected `&Matrix<f64, ..., ..., ...>`, found `&Matrix<..., ..., ..., ...>`
```
