### ISSUE TITLE
Crates.io version not updated.

### ISSUE THREAD

**Issue by overheat** [jmagnuson/ahrs-rs#38]
Need this:
```
ahrs = { version = "0.6", default-features = false }
nalgebra = { version = "0.31.4", default-features = false }
```
the nalgebra version is not updated. 
According to README, nalgebra version should be `0.32`

**Comment by dimpolo** [comment]
Is there anything blocking this?

**Comment by jmagnuson** [comment]
Thanks for the ping, I got busy with things and forgot to follow up. [v0.7.0](https://crates.io/crates/ahrs/0.7.0) has been published to crates.io!
